# Needed environment variables:
# HOST
# SSH_PUBKEY
# SSH_USER
# SSHPASS

addons:
  apt:
    packages:
      - npm

install:
  - echo "$SSH_PUBKEY" >> $HOME/.ssh/known_hosts

jobs:
  include:
    - stage: test
    script:
      - npm install
      - npm test
